openapi: 3.2.0
info:
  title: Getting Started with Passport Global Void API
  description: 'Introduction


    Passport Global''s API is designed to allow for quick integration to begin selling and shipping internationally.'
  version: '3.15'
  x-logo:
    url: PassportLogo.svg
    background: '#FAFAFA'
    altText: Logo Passport added via API Definition
servers:
- url: https://api-stg.passportshipping.com/v3
tags:
- name: Void
paths:
  /void/{code}:
    post:
      tags:
      - Void
      summary: Void an existing shipping label
      parameters:
      - in: path
        name: code
        schema:
          type: string
        required: true
        description: Uses the tracking code returned by /ship endpoint
      responses:
        200:
          description: (OK) label voided
        400:
          description: Bad Request, with an error message for non-voidable shipments
        404:
          description: Not Found, for invalid tracking codes
      operationId: postVoidByCode
      x-operation-id-source: derived
